version: "3"

services:
  api:
    container_name: my-api
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    container_name: my-mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: facilityManage
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: facilityManage
      MYSQL_HOST_NAME: facilityManage

volumes:
  data:
    driver: local

networks:
  app-network:
    driver: bridge
